name: Generate API Docs

on:
  push:
    branches:
      - main
      - devel

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Generate API Docs
        run: npx jsdoc2md *.js > API.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add API.md
          git commit -m "Generate API documentation"
          git push
