name: Lint

on:
  push:
    branches:
      - main
      - devel
      - '!temporary-docs-branch' # Ignore changes to the temporary branch
  pull_request:
    branches:
      - main
      - devel
      - '!temporary-docs-branch' # Ignore changes to the temporary branch

jobs:
  lintcode:
    name: Server JS lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install
    - run: npm run lint
